In [12]:
import numpy as np
import pandas as pd

In [13]:
Dict={"Text":["people watch Vidyantra","Vidyantra watch Vidyantra","people write Vidyantra","Vidyantra write comments"],"output":[1,1,0,0]}
df=pd.DataFrame(Dict)

In [14]:
df

,Text,output
0,people watch Vidyantra,1
1,Vidyantra watch Vidyantra,1
2,people write Vidyantra,0
3,Vidyantra write comments,0


In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv=CountVectorizer()

In [17]:
bow=cv.fit_transform(df["Text"])

In [18]:
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'vidyantra': 2, 'write': 4, 'comments': 0}


In [19]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 1 0]]
[[0 0 2 1 0]]


In [20]:
print(cv.transform(["Vidyantra watch the write comments"]).toarray())

[[1 0 1 1 1]]


# 🎥 Introductory Video Script for **Vidyantra**

**[Opening Scene – Futuristic Visuals]**
*Background: Animated data streams, glowing neural networks, and circuit boards forming the Vidyantra logo.*

🎙️ **Narration (You):**
"Welcome to **Vidyantra** — your one-stop platform for mastering the world of **Data Science** in depth. In today’s world, data isn’t just numbers. It’s the new fuel that drives businesses, innovations, and discoveries. And here at Vidyantra, we help you turn that fuel into power."

---

**[Scene 2 – About the Platform]**
*Visuals: Students coding, graphs transforming into insights, AI models running on screen.*

🎙️ **Narration:**
"Vidyantra is designed for learners who want to go **beyond surface-level tutorials**. From **Python, Machine Learning, and NLP**, to **Deep Learning, Data Analysis, and AI applications** — here, you’ll find **complete, structured, and practical learning paths**.

Every concept is explained in detail, paired with real-world projects, so you don’t just learn, you build. Our goal is simple: to create **industry-ready data scientists**."

---

**[Scene 3 – About You (Founder’s Journey)]**
*Visuals: Timeline animation of your education, projects, teaching, and achievements.*

🎙️ **Narration:**
"My name is **Hemant Mishra**, and I’m the founder of Vidyantra. I come from a strong academic and professional background in Data Science — with an **M.Tech from IIT Kharagpur** and a **B.Tech from Bharati Vidyapeeth, Pune**.

I’ve worked on projects ranging from **hotel booking prediction models** and **stock price forecasting with LSTMs**, to **sentiment analysis using NLP**, and even **scientific crystallization process modeling**.

As a **Professor at Geeks of Gurukul**, I’ve trained hundreds of students in **Python, Machine Learning, DSA, and AI**, while also mentoring them on projects and career growth. My teaching was recognized when I received the **Best Professor Award in 2025**."

---

**[Scene 4 – Why Vidyantra is Different]**
*Visuals: Split-screen of “Other Platforms = Surface Learning” vs. “Vidyantra = Depth + Projects + Career Guidance”.*

🎙️ **Narration:**
"What makes Vidyantra unique is **our depth and approach**. We don’t just teach algorithms — we teach you **why they work, how to optimize them, and how to apply them in real-world scenarios**.

Whether you’re a beginner or a working professional, you’ll find **personalized pathways**, **hands-on projects**, and **career-focused training**."

---

**[Scene 5 – Call to Action]**
*Visuals: Motivational shots of learners presenting projects, AI visuals, futuristic labs.*

🎙️ **Narration:**
"So, if you’re ready to transform your career and step into the world of Data Science with confidence, join us at **Vidyantra**. Together, let’s decode data, build intelligence, and create the future."

**[Closing Screen]**
*Vidyantra Logo + Website/YouTube/Community handles*
Tagline: **“Vidyantra – Where Data Meets Wisdom.”**

---

👉 This script gives you a professional yet inspiring introduction for your startup, positioning **Vidyantra** as a **trusted, in-depth, and visionary platform for Data Science** while also highlighting your strong credibility.

Would you like me to also create a **shorter version (1–1.5 minutes)** for platforms like **YouTube intro, Instagram reel, or LinkedIn video**? That way, you’ll have both a **full-length detailed intro** and a **quick pitch version**.'''

In [28]:
cv1=CountVectorizer(ngram_range=(1,2))

In [29]:
bow1=cv1.fit_transform(df["Text"])

In [30]:
cv1.vocabulary_

{'people': 1,
 'watch': 7,
 'vidyantra': 4,
 'people watch': 2,
 'watch vidyantra': 8,
 'vidyantra watch': 5,
 'write': 9,
 'people write': 3,
 'write vidyantra': 11,
 'comments': 0,
 'vidyantra write': 6,
 'write comments': 10}

In [32]:
print(bow1[0].toarray())
print(bow1[1].toarray())
print(bow1[2].toarray())
print(bow1[3].toarray())

[[0 1 1 0 1 0 0 1 1 0 0 0]]
[[0 0 0 0 2 1 0 1 1 0 0 0]]
[[0 1 0 1 1 0 0 0 0 1 0 1]]
[[1 0 0 0 1 0 1 0 0 1 1 0]]


In [34]:
print(cv1.transform(["Vidyantra watch the write comments"]).toarray())

[[1 0 0 0 1 1 0 1 0 1 1 0]]


In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
tfidf=TfidfVectorizer()

In [45]:
tfidf.fit_transform(df["Text"]).toarray()

array([[0.        , 0.64043405, 0.42389674, 0.64043405, 0.        ],
       [0.        , 0.        , 0.7979221 , 0.60276058, 0.        ],
       [0.        , 0.64043405, 0.42389674, 0.        , 0.64043405],
       [0.72664149, 0.        , 0.37919167, 0.        , 0.5728925 ]])

In [51]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.91629073 1.51082562 1.         1.51082562 1.51082562]
['comments' 'people' 'vidyantra' 'watch' 'write']


In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
OHE=OneHotEncoder()

In [65]:
OHE.fit_transform(df[["Text"]]).toarray()

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])